apiVersion: apps/v1
kind: Deployment
metadata:
  name: tg1
  namespace: mytg
  labels:
    app: mydb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mydb
  template:
    metadata:
      labels:
        app: mydb
    spec:
       containers:
         - name: mydb1
           image: mysql:5.6.42
           ports:
            - containerPort: 3306
           env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
               secretKeyRef:
                        name: mytg-secret
                        key: mypass 
