apiVersion: v1
kind: Service
metadata:
  name: tgsvc
  namespace: mytg
spec:
  type: NodePort
  selector:
    app: cement
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32000
